services:
    postgres:
        image: postgres:18
        environment:
            POSTGRES_DB: order_management
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

    backend-tests:
        build:
            context: ./backend
            dockerfile: Dockerfile.test
        container_name: backend-tests
        restart: "no"

    backend:
        build: ./backend
        depends_on:
            - postgres
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_management
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
        ports:
            - "8080:8080"
