ALTER TABLE customers
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
    USING created_at AT TIME ZONE 'UTC';

ALTER TABLE customers
    ALTER COLUMN created_at DROP DEFAULT;


ALTER TABLE products
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
    USING created_at AT TIME ZONE 'UTC';

ALTER TABLE products
    ALTER COLUMN created_at DROP DEFAULT;


ALTER TABLE orders
ALTER COLUMN order_date TYPE TIMESTAMP WITH TIME ZONE
    USING order_date AT TIME ZONE 'UTC';

ALTER TABLE orders
    ALTER COLUMN order_date DROP DEFAULT;